<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c681adc2-7efe-4014-8b7c-96b1225cfe4e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GokeHyb\GokeHyb.csproj">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\GokeWebServer\GokeWebServer\GokeWebServer.csproj" />
    <ProjectReference Include="..\GokeWeb\GokeWeb\GokeWeb.csproj" />
  </ItemGroup>

</Project>
